ppackage com.easybank.enums;

public enum ComplaintActions {
	MOVED_TO_SUPER_ADMIN,BRANCH_ROLLBACK_TO_USER,REGION_ROLLBACK_TO_BRANCH,ADMIN_ROLLBACK_TO_USER,

	USER_UPDATED,BRANCH_UPDATED,REGION_UPDATED,USER_SUBMIT,USER_REQUEST_TO_CLOSE
}
